### PR TITLE
Verification of latest JMSML source data

### PR DESCRIPTION
**Pull request by abouffard**
Added image files generated from the Runtime exporter using legacy
renderer style files built with the latest JMSML data.  Added new
columns to illustrate the images so they can be compared to the standard
and the benchmark Runtime export.  Added to the README to explain other
changes.

### CODE REVIEW

**Comment by abouffard** [comment]
@csmoore - verification of the latest JMSML data changes are reflected here.  Please review and merge/manage as desired.  Given my work and vacation schedule over the next four weeks, I won't be able to address any significant changes until after August 16th, but will be happy to reply to your questions/comments over the next week.

**Comment by csmoore** [comment]
Thanks - this looks pretty close,  I am however puzzled by the remaining issues shown in: 

https://github.com/abouffard/mil2525-testing/blob/jmsml-update/mil2525c/Mil252C-Test-Results-JMSML-Issues-Only.md  
https://github.com/abouffard/mil2525-testing/blob/jmsml-update/mil2525bc2/Mil2525Bc2-Test-Results-JMSML-Issues-Only.md

Since those errors such as the "Tropopause" symbols were definitely fixed in [mil2525d-lines-areas-labels-base-template.stylx](https://github.com/Esri/military-features-data/blob/v.next/data/mil2525d/core_data/stylxfiles/mil2525d-lines-areas-labels-base-template.stylx) - are you sure you  were using the latest versus of that style with the merge?

**Comment by abouffard** [comment]
I thought I had updated to the latest, but perhaps not.  I'll check and update as needed and can run the tests again pretty quickly.

**Comment by abouffard** [comment]
@csmoore - sorry about that.  Yes, much better results found when using the very latest line-area-label stylx.  PR updated with another commit.  That should do it.  Thanks again.

**Comment by abouffard** [comment]
@csmoore - I also wanted to make sure you noted that the BC2 Space SIGINT frames are now correct in JMSML.

**Comment by csmoore** [comment]
This output looks pretty good - only concerns noted in https://github.com/Esri/joint-military-symbology-xml/pull/319#issuecomment-234105967 & https://github.com/Esri/joint-military-symbology-xml/pull/319#issuecomment-234533175 

@dbarnes1 @joebayles  if you do rerun these tests go ahead and use this same branch (it will already have the tables set up for you)

**Comment by csmoore** [comment]
opps - didn't notice this was being merged into master and not a new branch - I'm going to back out that commit/merge

**Comment by csmoore** [comment]
Reverted those changes in master and put in separate branch at: https://github.com/csmoore/mil2525-testing/tree/JMSML-Diff-Testing

**Pull request merged**
